In [6]:
# Exercicio 01 -Manipulando dataframes com Pandas.
# A) Abra o arquivo world_happiness_report_2015.csv e o aloque em um dataframe
import pandas as pd

# Mapear o diretorio do documento

caminho = 'C:\\Users\\FIC\\Documents\\Adriano Python\\003 - Arquivos\\'

arquivo = 'world_happiness_report_2015.csv'

# Carregar o arquivo para um dataframe

df = pd.read_csv(caminho + arquivo)

In [7]:
# B) Verifique o cabe√ßalho

df.head()

,country,region,happiness rank,happiness score,standard error,economy (GDP per Capita),family,health (Life Expectancy),freedom,trust (Government Corruption),generosity,dystopia residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [11]:
# C) Quais as colunas desse dataframe

df.info

<bound method DataFrame.info of          country                           region  happiness rank  \
0    Switzerland                   Western Europe               1
1        Iceland                   Western Europe               2
2        Denmark                   Western Europe               3
3         Norway                   Western Europe               4
4         Canada                    North America               5
..           ...                              ...             ...
159       Rwanda               Sub-Saharan Africa             154
160        Benin               Sub-Saharan Africa             155
161        Syria  Middle East and Northern Africa             156
162      Burundi               Sub-Saharan Africa             157
163         Togo               Sub-Saharan Africa             158

     happiness score  standard error  economy (GDP per Capita)   family  \
0              7.587         0.03411                   1.39651  1.34951
1              7.561         0.04884                   1.30232  1.40223
2              7.527         0.03328                   1.32548  1.36058
3              7.522         0.03880                   1.45900  1.33095
4              7.427         0.03553                   1.32629  1.32261
..               ...             ...                       ...      ...
159            3.465         0.03464                   0.22208  0.77370
160            3.340             NaN                   0.28665  0.35386
161            3.006         0.05015                   0.66320  0.47489
162            2.905         0.08658                   0.01530  0.41587
163            2.839         0.06727                   0.20868  0.13995

     health (Life Expectancy)  freedom  trust (Government Corruption)  \
0                     0.94143  0.66557                        0.41978
1                     0.94784  0.62877                        0.14145
2                     0.87464  0.64938                        0.48357
3                     0.88521  0.66973                        0.36503
4                     0.90563  0.63297                        0.32957
..                        ...      ...                            ...
159                   0.42864  0.59201                        0.55191
160                   0.31910  0.48450                        0.08010
161                   0.72193  0.15684                        0.18906
162                   0.22396  0.11850                        0.10062
163                   0.28443  0.36453                        0.10731

     generosity  dystopia residual
0       0.29678            2.51738
1       0.43630            2.70201
2       0.34139            2.49204
3       0.34699            2.46531
4       0.45811            2.45176
..          ...                ...
159     0.22628            0.67042
160     0.18260                NaN
161     0.47179            0.32858
162     0.19727                NaN
163     0.16681                NaN

[164 rows x 12 columns]>

In [10]:
# D) Quais os tipos de dados temos no dataframe

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   country                        164 non-null    object
 1   region                         164 non-null    object
 2   happiness rank                 164 non-null    int64
 3   happiness score                156 non-null    float64
 4   standard error                 163 non-null    float64
 5   economy (GDP per Capita)       164 non-null    float64
 6   family                         164 non-null    float64
 7   health (Life Expectancy)       164 non-null    float64
 8   freedom                        164 non-null    float64
 9   trust (Government Corruption)  164 non-null    float64
 10  generosity                     164 non-null    float64
 11  dystopia residual              150 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 15.5+ KB

In [12]:
# E) H√° valores faltantes ou nulo? Em quais coluna?

# SIM

#  standard error                 163 non-null    
#  dystopia residual              150 non-null

In [16]:
# F) Renomeie as vari√°veis como segue

df = df.rename(columns={
    'happiness rank':'rank felicidade',
    'happiness score':'score_felicidade',
    'standard error':'stand_error',
    'economy (GDP per Capita)':'PIB'}
    )

df.head()

,country,region,rank felicidade,score_felicidade,stand_error,PIB,family,health (Life Expectancy),freedom,trust (Government Corruption),generosity,dystopia residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176